[project]
name = "indexer"
version = "0.1.0"
description = "A script to add data to Elasticsearch"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "elasticsearch<9",
    "orjson>=3.10.12",
]
